### ISSUE TITLE
Suggestion for simpler include syntax

### ISSUE THREAD

**Issue by rnkn** [mjrusso/mountain#2]
Feel free to shoot me down here, but how about the following:

```
[[ include: Foo.fountain]]
```

As I see it, the advantages of dropping the `#` and appending a `:` are:
- "It's cleaner" -- Justin Timberlake
- It conforms more with the YAML-style metadata/title-page frontmatter
- If the include does not resolve to a file, they can be parsed as a regular note and still make sense, e.g.

```
[[ include: that part where she goes back for the dog.. ]]
```
- ...but it's more likely a writer will write, which will be ignored:

```
[[ include that idea with the monkey butler stealing the martini ]]
```

Thoughts?

**Comment by drusso** [comment]
I like the cleaner syntax. 

One drawback to note, however, is that when the `#` and `:` are not required it's no longer possible to detect (with good certainty) the author's intent to include a fountain partial. As a side-effect, we couldn't issue a warning to the user in the case that the include does not resolve to a fountain partial file, which we might want to do if there's a typo in the filename.

@rnkn, @mjrusso: Thoughts?

**Comment by drusso** [comment]
On second thought, the `.fountain` would still be in the include call. Perhaps that is enough to detect intent to include a fountain partial, so we could still raise a warning if a matching file is not found.

**Comment by rnkn** [comment]
I think still require `:` in the include. So...

```
[[ include: that part where she goes back for the dog ]]
```

...would be parsed first as an intent to include a file, the file would not be found (maybe raise a warning), then would be parsed as a regular note.

```
[[ include that idea with the monkey butler stealing the martini ]]
```

...would always be parsed as a note (since I think it's more likely the way someone would type.

In the event that someone has a file called `./that part where she goes back for the dog` they'd at least get a warning if they misspelt it.

Are you guys brothers?

**Comment by mjrusso** [comment]
I've been hoping that first-class metadata support would come to Fountain at some point (specifically to make it easier to write tooling that operates on top of Fountain documents), but alas, it doesn't look like it's going to happen at any point soon. (These ["Mountain directives"](https://github.com/mjrusso/mountain/#directives) certainly haven't helped to further the cause.)

What I'd really like to see is metadata encoded in a special metadata element (something like `{{ }}`), instead of re-using the notes element...

Anyways, since I'm now much less optimistic that this is going to happen, I'm not opposed to this change. (I'm pretty sure that `include:` was my initial syntax.)

What do we do with `#reference`? Switch it to `reference:` instead? (And, discussion in #3 notwithstanding, keep `/reference` the same?)

**Comment by mjrusso** [comment]
(And yes, @drusso is my brother :grinning:)

**Comment by rnkn** [comment]
I think you already took the better path. To a Fountain/Mountain newcomer it can be explained thusly: metadata takes the form of `key: value` at the top of the file, or sometimes enclosed in notes throughout the file. (It's not exactly this, e.g. you can't have `[[ title: You and Me and Everyone at Arby's ]]` halfway through a file, but if shown an example it's easy to understand, methinks.)

I reckon `reference:` with its partner `/reference` is the way to go. People already write "/sarcasm" on the www so it should be immediately obvious what's going on.

**Comment by mjrusso** [comment]
Implemented as per #4.

**Comment by rnkn** [comment]
👍

Wonderful work. I foresee Mountain syntax one day becoming a part of Fountain.

**Comment by mjrusso** [comment]
And that would be a joyous day indeed!

I wonder if @nyousefi could be persuaded to add first-class split/join support to Highland... ;)
